name: Smoke Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    environment: Demo Blaze
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run smoke tests
      run: npm run smoke
      env:
        DEMO_BLAZE_USER_NAME: ${{ secrets.DEMO_BLAZE_USER_NAME }}
        DEMO_BLAZE_PASSWORD: ${{ secrets.DEMO_BLAZE_PASSWORD }}
        DEMO_BLAZE_API_BASE_URL: ${{ vars.DEMO_BLAZE_API_BASE_URL }}
        NEXUS_6_PRODUCT_ID: ${{ vars.NEXUS_6_PRODUCT_ID }}
        MACBOOK_PRO_PRODUCT_ID: ${{ vars.MACBOOK_PRO_PRODUCT_ID }}
        ASUS_FULL_HD_PRODUCT_ID: ${{ vars.ASUS_FULL_HD_PRODUCT_ID }}
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: smoke-test-results
        path: dist/
        retention-days: 7
